services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: trip-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - trip-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: trip-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - trip-network

networks:
  trip-network:
    driver: bridge