FROM nginx:alpine

# Limpiar contenido default
RUN rm -rf /usr/share/nginx/html/*

# Copiar tus archivos estáticos
COPY index.html /usr/share/nginx/html/
COPY dist/main.js /usr/share/nginx/html/

# Copiar configuración de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]